# Evaluation Metrics for Generative Modeling on Spatial Transcriptomics

**Data:** Zhuang ABCA mouse-brain spatial-transcriptomics slides.

This notebook is organized as one linear workflow:

1. **Train model checkpoints**
2. **Generate cells from each checkpoint**
3. **Train the held-out classifier and reconstruction probes**
4. **Run the same evaluation suite for every model**
5. **Compile the per-model metric CSVs**

Each model has its own cell at every model-specific stage. All models use the same shared whitened PCA-50 expression basis and standardized coordinate convention. Paths are relative to `notebooks/` unless a cell explicitly changes directory.

## 0. Environment and shared preprocessing

This prerequisite is run before the five model-comparison stages. It creates the common source/target evaluation pickle, the held-out classifier-slide pickle, and the `shared_pca.npz` file replayed by OT-CFM and WFM.

Slides:

- Source: ABCA `1.024`
- Evaluation target: ABCA `1.025`
- Held-out classifier training slide: ABCA `1.026`

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
UV_LINK_MODE=copy uv sync --extra pipeline --extra nicheflow --extra classifier

In [ ]:
import importlib
import sys

import numpy as np
import pandas as pd
import torch

print("python:", sys.executable)
print("torch:", torch.__version__, "cuda:", torch.version.cuda)
for module in ("ot", "squidpy", "jaxtyping"):
    try:
        importlib.import_module(module)
        print(f"{module}: available")
    except Exception as exc:
        print(f"{module}: unavailable ({exc})")

In [ ]:
%%bash
set -euo pipefail
uv run python -m paired_slides_eval.adapters.prepare_shared_slides \
  --source ../../nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.024.h5ad \
  --target ../../nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.025.h5ad \
  --classifier_slide ../../nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.026.h5ad \
  --ct_key class \
  --n_pcs 50 \
  --out_pair ../data/abca_pair.pkl \
  --out_classifier ../data/abca_1.026_clf.pkl

cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.adapters.otcfm_export \
  --pair data/abca_pair.pkl \
  --out data/shared_pca.npz

In [ ]:
import pickle
from pathlib import Path

pair_path = Path("../data/abca_pair.pkl")
classifier_path = Path("../data/abca_1.026_clf.pkl")
stats_path = Path("../data/shared_pca.npz")

for path in (pair_path, classifier_path, stats_path):
    if not path.exists():
        raise FileNotFoundError(path)

with pair_path.open("rb") as fh:
    pair = pickle.load(fh)

PAIR_PKL = str(pair_path)
print("shared PCA dimension:", pair.X_pca.shape[1])
print("slides:", pair.timepoints_ordered)
print("shared artifacts ready")

## 1. Train model checkpoints

Run each model in its own cell. GPU-heavy cells should run inside an allocation. The NicheFlow commands remain project-entrypoint placeholders because that external checkout controls its trainer.

### 1.1 OT-CFM — expression only

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
PY=.venv/bin/python
$PY fm_mnist/scripts/train_cfm_spatial.py \
  --data nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.025.h5ad \
  --pca_stats eval_metrics/data/shared_pca.npz \
  --out fm_mnist/outputs/cfm_shared50_1025

### 1.2 OT-CFM — expression + spatial coordinates

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
PY=.venv/bin/python
$PY fm_mnist/scripts/train_cfm_spatial.py \
  --data nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.025.h5ad \
  --pca_stats eval_metrics/data/shared_pca.npz \
  --spatial_key spatial \
  --out fm_mnist/outputs/cfm_spatial_shared50_1025

### 1.3 NicheFlow CFM

In [ ]:
%%bash
set -euo pipefail
cd ../../nicheflow_mba
.venv/bin/python nicheflow/train.py \
  experiment=nicheflow/cfm/abca \
  hydra.run.dir=outputs/nicheflow_cfm_abca \
  callbacks.model_checkpoint.dirpath=$PWD/ckpts \
  callbacks.model_checkpoint.filename=NicheFlow_CFM_ABCA \
  callbacks.model_checkpoint.save_last=false
echo "wrote ckpts/NicheFlow_CFM_ABCA.ckpt"

### 1.4 NicheFlow VFM

In [ ]:
%%bash
set -euo pipefail
cd ../../nicheflow_mba
.venv/bin/python nicheflow/train.py \
  experiment=nicheflow/vfm/abca \
  hydra.run.dir=outputs/nicheflow_vfm_abca \
  callbacks.model_checkpoint.dirpath=$PWD/ckpts \
  callbacks.model_checkpoint.filename=NicheFlow_VFM_ABCA \
  callbacks.model_checkpoint.save_last=false
echo "wrote ckpts/NicheFlow_VFM_ABCA.ckpt"

### 1.5 WFM DeepSet — expression only

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR"
uv run --no-sync python wfm_mba/scripts/train_hydra.py \
  experiment=expr \
  data.point_state=expr \
  output_dir=wfm_mba/outputs/wfm_expr_converged_seed0 \
  train.steps=100000 \
  wandb.name=abca-1025-expr-seed0

### 1.6 WFM DeepSet — expression + relative coordinates

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR"
uv run --no-sync python wfm_mba/scripts/train_hydra.py \
  experiment=joint_relxy \
  data.point_state=joint_relxy \
  output_dir=wfm_mba/outputs/wfm_joint_relxy_converged_seed0 \
  train.steps=100000 \
  wandb.name=abca-1025-joint-relxy-seed0

### 1.7 WFM Transformer — expression only

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR"
uv run --no-sync python wfm_mba/scripts/train_hydra.py \
  experiment=expr_transformer \
  data.point_state=expr \
  output_dir=wfm_mba/outputs/wfm_expr_transformer_seed0 \
  train.steps=100000 \
  wandb.name=abca-1025-expr-transformer-seed0

### 1.8 WFM Transformer — expression + relative coordinates

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR"
uv run --no-sync python wfm_mba/scripts/train_hydra.py \
  experiment=joint_relxy_transformer \
  data.point_state=joint_relxy \
  output_dir=wfm_mba/outputs/wfm_joint_relxy_transformer_seed0 \
  train.steps=100000 \
  wandb.name=abca-1025-joint-relxy-transformer-seed0

### 1.9 WFM faithful Transformer — expression only

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR"
uv run --no-sync python wfm_mba/scripts/train_hydra.py \
  experiment=expr_transformer_faithful \
  data.point_state=expr \
  output_dir=wfm_mba/outputs/wfm_expr_transformer_faithful_seed0 \
  train.steps=100000 \
  wandb.name=abca-1025-expr-transformer-faithful-seed0

### 1.10 WFM faithful Transformer — expression + relative coordinates

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR"
uv run --no-sync python wfm_mba/scripts/train_hydra.py \
  experiment=joint_relxy_transformer_faithful \
  data.point_state=joint_relxy \
  output_dir=wfm_mba/outputs/wfm_joint_relxy_transformer_faithful_seed0 \
  train.steps=100000 \
  wandb.name=abca-1025-joint-relxy-transformer-faithful-seed0

## 2. Generate cells

Every cell below consumes exactly one checkpoint and writes one evaluator artifact.

Expression-only WFM assigns generated expression points to a randomized target-niche spatial scaffold: point 0 retains the target centroid while neighbor coordinates are permuted. These coordinates are a spatial-null scaffold, not generated spatial structure. Joint WFM generates relative coordinates but still anchors each niche at a real target centroid.

### 2.1 OT-CFM — expression only

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
FM=../fm_mnist
DATA=../nicheflow_mba/data
uv run python -m paired_slides_eval.generate \
  generator=otcfm \
  target=$DATA/adata_Zhuang_Zhuang-ABCA-1.025.h5ad \
  source=null \
  checkpoint=$FM/outputs/cfm_shared50_1025/ckpt_final.pt \
  generator.fm_root=$FM \
  generated_out=artifacts/otcfm_shared50_1025/generated.h5ad

### 2.2 OT-CFM — expression + spatial coordinates

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
FM=../fm_mnist
DATA=../nicheflow_mba/data
uv run python -m paired_slides_eval.generate \
  generator=otcfm_spatial \
  source=$DATA/adata_Zhuang_Zhuang-ABCA-1.025.h5ad \
  target=$DATA/adata_Zhuang_Zhuang-ABCA-1.025.h5ad \
  checkpoint=$FM/outputs/cfm_spatial_shared50_1025/ckpt_final.pt \
  generator.fm_root=$FM \
  generated_out=artifacts/otcfm_spatial_shared50_1025/generated.h5ad

### 2.3 NicheFlow CFM

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
../nicheflow_mba/.venv/bin/python -m paired_slides_eval.generate \
  generator=nicheflow \
  source=../nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.024.h5ad \
  target=../nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.025.h5ad \
  checkpoint=../nicheflow_mba/ckpts/NicheFlow_CFM_ABCA.ckpt \
  generated_out=artifacts/nicheflow_cfm_unaligned/generated.h5ad

### 2.4 NicheFlow VFM

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
../nicheflow_mba/.venv/bin/python -m paired_slides_eval.generate \
  generator=nicheflow \
  generator.variant=vfm \
  source=../nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.024.h5ad \
  target=../nicheflow_mba/data/adata_Zhuang_Zhuang-ABCA-1.025.h5ad \
  checkpoint=../nicheflow_mba/ckpts/NicheFlow_VFM_ABCA.ckpt \
  generated_out=artifacts/nicheflow_vfm_unaligned/generated.h5ad

### 2.5 WFM DeepSet — expression only

In [1]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR" eval_metrics/artifacts/wfm_expr_converged_seed0
uv run --no-sync python wfm_mba/scripts/sample_checkpoint.py \
  --checkpoint wfm_mba/outputs/wfm_expr_converged_seed0/ckpt_best.pt \
  --out eval_metrics/artifacts/wfm_expr_converged_seed0/generated.npz \
  --n_samples 512 --steps 50 --seed 0

saved samples to eval_metrics/artifacts/wfm_expr_converged_seed0/generated.npz

### 2.6 WFM DeepSet — expression + relative coordinates

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR" eval_metrics/artifacts/wfm_joint_relxy_converged_seed0
uv run --no-sync python wfm_mba/scripts/sample_checkpoint.py \
  --checkpoint wfm_mba/outputs/wfm_joint_relxy_converged_seed0/ckpt_best.pt \
  --out eval_metrics/artifacts/wfm_joint_relxy_converged_seed0/generated.npz \
  --n_samples 512 --steps 50 --seed 0

### 2.7 WFM Transformer — expression only

In [2]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR" eval_metrics/artifacts/wfm_expr_transformer_seed0
uv run --no-sync python wfm_mba/scripts/sample_checkpoint.py \
  --checkpoint wfm_mba/outputs/wfm_expr_transformer_seed0/ckpt_best.pt \
  --out eval_metrics/artifacts/wfm_expr_transformer_seed0/generated.npz \
  --n_samples 512 --steps 50 --seed 0

/work/magroup/shared/enfuzers/generative_modeling/wfm_mba/wfm_mba/model.py:91: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.encoder = nn.TransformerEncoder(layer, num_layers=int(depth))

saved samples to eval_metrics/artifacts/wfm_expr_transformer_seed0/generated.npz

### 2.8 WFM Transformer — expression + relative coordinates

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR" eval_metrics/artifacts/wfm_joint_relxy_transformer_seed0
uv run --no-sync python wfm_mba/scripts/sample_checkpoint.py \
  --checkpoint wfm_mba/outputs/wfm_joint_relxy_transformer_seed0/ckpt_best.pt \
  --out eval_metrics/artifacts/wfm_joint_relxy_transformer_seed0/generated.npz \
  --n_samples 512 --steps 50 --seed 0

### 2.9 WFM faithful Transformer — expression only

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR" eval_metrics/artifacts/wfm_expr_transformer_faithful_seed0
uv run --no-sync python wfm_mba/scripts/sample_checkpoint.py \
  --checkpoint wfm_mba/outputs/wfm_expr_transformer_faithful_seed0/ckpt_best.pt \
  --out eval_metrics/artifacts/wfm_expr_transformer_faithful_seed0/generated.npz \
  --n_samples 512 --steps 50 --seed 0

### 2.10 WFM faithful Transformer — expression + relative coordinates

In [ ]:
%%bash
set -euo pipefail
cd ../..  # -> generative_modeling/
export UV_CACHE_DIR=.uv-cache MPLCONFIGDIR=/tmp/mpl-${USER:-wfm} PYTHONPATH=wfm_mba CUDA_VISIBLE_DEVICES=0
mkdir -p "$MPLCONFIGDIR" eval_metrics/artifacts/wfm_joint_relxy_transformer_faithful_seed0
uv run --no-sync python wfm_mba/scripts/sample_checkpoint.py \
  --checkpoint wfm_mba/outputs/wfm_joint_relxy_transformer_faithful_seed0/ckpt_best.pt \
  --out eval_metrics/artifacts/wfm_joint_relxy_transformer_faithful_seed0/generated.npz \
  --n_samples 512 --steps 50 --seed 0

## 3. Train evaluation probes

These probes train only on held-out slide `1.026`, after generator artifacts have been produced. They are frozen during evaluation. The classifier predicts a centroid cell type from the expression profiles of its 10 nearest spatial neighbors; coordinates select KNN membership and are then discarded, and the centroid itself is masked.

### 3.1 Spatial cell-type classifier

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.classifier.train \
  experiment=classifier/abca_spatial \
  data.datamodule.data_fp=$PWD/data/abca_1.026_clf.pkl \
  data.n_classes=20 \
  data.n_pcs=50 \
  logger=tensorboard \
  hydra.run.dir=outputs/clf_gene_train \
  callbacks.model_checkpoint.dirpath=$PWD/ckpts \
  callbacks.model_checkpoint.filename=clf_gene \
  callbacks.model_checkpoint.save_last=false
echo "wrote ckpts/clf_gene.ckpt"

### 3.2 Masked-centroid expression regressor

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.classifier.train \
  experiment=classifier/abca_spatial_regressor \
  data.datamodule.data_fp=$PWD/data/abca_1.026_clf.pkl \
  data.n_classes=20 \
  data.n_pcs=50 \
  logger=tensorboard \
  hydra.run.dir=outputs/recon_train \
  callbacks.model_checkpoint.dirpath=$PWD/ckpts \
  callbacks.model_checkpoint.filename=recon_spatial \
  callbacks.model_checkpoint.save_last=false
echo "wrote ckpts/recon_spatial.ckpt"

## 4. Run evaluation

Each model is evaluated independently against `data/abca_pair.pkl` with the same frozen probes and metric groups. Non-WFM outputs use `metrics_npc50_full.csv`; WFM outputs use `metrics_wfm_npc50.csv`.

Lower is better for distribution distances, C2ST should approach 0.5, higher Moran correlation is better, lower Moran MAE is better, and smaller classifier/reconstruction gaps are better. Regression metrics run only when a model supplies matched `gt_x/gt_pos`; unsupported groups are reported as skipped.

### 4.1 OT-CFM — expression only

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/otcfm_shared50_1025/generated.h5ad \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/otcfm_shared50_1025/metrics_npc50_full.csv

### 4.2 OT-CFM — expression + spatial coordinates

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/otcfm_spatial_shared50_1025/generated.h5ad \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/otcfm_spatial_shared50_1025/metrics_npc50_full.csv

### 4.3 NicheFlow CFM

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/nicheflow_cfm_unaligned/generated.h5ad \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/nicheflow_cfm_unaligned/metrics_npc50_full.csv

### 4.4 NicheFlow VFM

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/nicheflow_vfm_unaligned/generated.h5ad \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/nicheflow_vfm_unaligned/metrics_npc50_full.csv

### 4.5 WFM DeepSet — expression only

In [3]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/wfm_expr_converged_seed0/generated.npz \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/wfm_expr_converged_seed0/metrics_wfm_npc50.csv

warning: `VIRTUAL_ENV=/work/magroup/shared/enfuzers/generative_modeling/.venv` does not match the project environment path `.venv` and will be ignored; use `--active` to target the active environment instead
<frozen runpy>:128: RuntimeWarning: 'paired_slides_eval.evaluate' found in sys.modules after import of package 'paired_slides_eval', but prior to execution of 'paired_slides_eval.evaluate'; this may result in unpredictable behaviour
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/.venv/lib/python3.12/site-packages/docrep/decorators.py:43: SyntaxWarning: 'n_jobs' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/.venv/lib/python3.12/site-packages/docrep/decorators.py:43: SyntaxWarning: 'show_progress_bar' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/src/paired_slides_eval/metrics/morans.py:50: FutureWarning: Calling `spatial_neighbors` is deprecated and will be removed in squidpy v1.9.0. Use `spatial_neighbors_knn`, `spatial_neighbors_radius`, `spatial_neighbors_delaunay`, `spatial_neighbors_grid`, or `spatial_neighbors_from_builder` instead.
  sq.gr.spatial_neighbors(adata, coord_type="generic", n_neighs=n_neighs)

INFO     Creating graph using `None` transform and `1` libraries.

/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/src/paired_slides_eval/metrics/morans.py:50: FutureWarning: Calling `spatial_neighbors` is deprecated and will be removed in squidpy v1.9.0. Use `spatial_neighbors_knn`, `spatial_neighbors_radius`, `spatial_neighbors_delaunay`, `spatial_neighbors_grid`, or `spatial_neighbors_from_builder` instead.
  sq.gr.spatial_neighbors(adata, coord_type="generic", n_neighs=n_neighs)

INFO     Creating graph using `None` transform and `1` libraries.
target: 9962 cells, 50 features
generated: 512 niches x 68 points
test/c2st/acc            0.7345
test/c2st/auc            0.8050
test/c2st/gene_acc       0.6205
test/c2st/gene_auc       0.6606
test/c2st/nn             0.4766
test/c2st/nn_real_ref    0.7176
test/c2st/nn_std         0.1515
test/ct/acc              0.4336
test/ct/acc_gap          0.1759
test/ct/acc_gen          0.4141
test/ct/acc_real         0.5900
test/ct/f1               0.4147
test/ct/prop_jsd         0.0105
test/ct/prop_kl          0.2027
test/ct/prop_tv          0.0977
test/mmd2/pos            0.0843
test/mmd2/x              0.0084
test/moran/corr          -0.3163
test/moran/gen_mean      -0.0001
test/moran/mae           0.1888
test/moran/real_mean     0.1887
test/ot_w1/pos           0.4412
test/ot_w1/x             5.6463
test/ot_w2/pos           0.5210
test/ot_w2/x             5.7506
test/pos/mae             1.3198
test/pos/mse             2.5922
test/recon/mse_gap       0.0571
test/recon/mse_gen       0.8185
test/recon/mse_real      0.8756
test/x/mae               1.0431
test/x/mse               1.8333
notes: coords auto -> passthrough (generated per-axis std [1.2000000476837158, 1.2799999713897705] vs target raw std [0.49, 0.73]; standardised coords have std ~1); ct/acc_real from a fixed seeded sample of 2000 real target centroids (model-independent), not the generated-centroid pairing; recon/mse_real from a fixed seeded sample of 2000 real target centroids (model-independent), not the generated-centroid pairing

saved reports/wfm_expr_converged_seed0/metrics_wfm_npc50.csv

### 4.6 WFM DeepSet — expression + relative coordinates

In [28]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/wfm_joint_relxy_converged_seed0/generated.npz \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/wfm_joint_relxy_converged_seed0/metrics_wfm_npc50.csv

warning: `VIRTUAL_ENV=/work/magroup/shared/enfuzers/generative_modeling/.venv` does not match the project environment path `.venv` and will be ignored; use `--active` to target the active environment instead
<frozen runpy>:128: RuntimeWarning: 'paired_slides_eval.evaluate' found in sys.modules after import of package 'paired_slides_eval', but prior to execution of 'paired_slides_eval.evaluate'; this may result in unpredictable behaviour
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/.venv/lib/python3.12/site-packages/docrep/decorators.py:43: SyntaxWarning: 'n_jobs' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/.venv/lib/python3.12/site-packages/docrep/decorators.py:43: SyntaxWarning: 'show_progress_bar' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/src/paired_slides_eval/metrics/morans.py:50: FutureWarning: Calling `spatial_neighbors` is deprecated and will be removed in squidpy v1.9.0. Use `spatial_neighbors_knn`, `spatial_neighbors_radius`, `spatial_neighbors_delaunay`, `spatial_neighbors_grid`, or `spatial_neighbors_from_builder` instead.
  sq.gr.spatial_neighbors(adata, coord_type="generic", n_neighs=n_neighs)

INFO     Creating graph using `None` transform and `1` libraries.

/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/src/paired_slides_eval/metrics/morans.py:50: FutureWarning: Calling `spatial_neighbors` is deprecated and will be removed in squidpy v1.9.0. Use `spatial_neighbors_knn`, `spatial_neighbors_radius`, `spatial_neighbors_delaunay`, `spatial_neighbors_grid`, or `spatial_neighbors_from_builder` instead.
  sq.gr.spatial_neighbors(adata, coord_type="generic", n_neighs=n_neighs)

INFO     Creating graph using `None` transform and `1` libraries.
target: 9962 cells, 50 features
generated: 512 niches x 68 points
test/c2st/acc            0.6855
test/c2st/auc            0.7368
test/c2st/gene_acc       0.6432
test/c2st/gene_auc       0.6870
test/c2st/nn             0.4487
test/c2st/nn_real_ref    0.7267
test/c2st/nn_std         0.1553
test/ct/acc              0.4316
test/ct/acc_gap          0.1857
test/ct/acc_gen          0.4043
test/ct/acc_real         0.5900
test/ct/f1               0.4106
test/ct/prop_jsd         0.0139
test/ct/prop_kl          0.2180
test/ct/prop_tv          0.1152
test/mmd2/pos            0.0004
test/mmd2/x              0.0085
test/moran/corr          0.8919
test/moran/gen_mean      0.0131
test/moran/mae           0.1756
test/moran/real_mean     0.1887
test/ot_w1/pos           0.0974
test/ot_w1/x             5.6745
test/ot_w2/pos           0.1214
test/ot_w2/x             5.7731
test/pos/mae             0.1277
test/pos/mse             0.0261
test/recon/mse_gap       0.0622
test/recon/mse_gen       0.8134
test/recon/mse_real      0.8756
test/x/mae               1.0404
test/x/mse               1.8228
notes: coords auto -> passthrough (generated per-axis std [1.0299999713897705, 0.9700000286102295] vs target raw std [0.49, 0.73]; standardised coords have std ~1); ct/acc_real from a fixed seeded sample of 2000 real target centroids (model-independent), not the generated-centroid pairing; recon/mse_real from a fixed seeded sample of 2000 real target centroids (model-independent), not the generated-centroid pairing

saved reports/wfm_joint_relxy_converged_seed0/metrics_wfm_npc50.csv

### 4.7 WFM Transformer — expression only

In [4]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/wfm_expr_transformer_seed0/generated.npz \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/wfm_expr_transformer_seed0/metrics_wfm_npc50.csv

warning: `VIRTUAL_ENV=/work/magroup/shared/enfuzers/generative_modeling/.venv` does not match the project environment path `.venv` and will be ignored; use `--active` to target the active environment instead
<frozen runpy>:128: RuntimeWarning: 'paired_slides_eval.evaluate' found in sys.modules after import of package 'paired_slides_eval', but prior to execution of 'paired_slides_eval.evaluate'; this may result in unpredictable behaviour
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/.venv/lib/python3.12/site-packages/docrep/decorators.py:43: SyntaxWarning: 'n_jobs' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/.venv/lib/python3.12/site-packages/docrep/decorators.py:43: SyntaxWarning: 'show_progress_bar' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/src/paired_slides_eval/metrics/morans.py:50: FutureWarning: Calling `spatial_neighbors` is deprecated and will be removed in squidpy v1.9.0. Use `spatial_neighbors_knn`, `spatial_neighbors_radius`, `spatial_neighbors_delaunay`, `spatial_neighbors_grid`, or `spatial_neighbors_from_builder` instead.
  sq.gr.spatial_neighbors(adata, coord_type="generic", n_neighs=n_neighs)

INFO     Creating graph using `None` transform and `1` libraries.

/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/src/paired_slides_eval/metrics/morans.py:50: FutureWarning: Calling `spatial_neighbors` is deprecated and will be removed in squidpy v1.9.0. Use `spatial_neighbors_knn`, `spatial_neighbors_radius`, `spatial_neighbors_delaunay`, `spatial_neighbors_grid`, or `spatial_neighbors_from_builder` instead.
  sq.gr.spatial_neighbors(adata, coord_type="generic", n_neighs=n_neighs)

INFO     Creating graph using `None` transform and `1` libraries.
target: 9962 cells, 50 features
generated: 512 niches x 68 points
test/c2st/acc            0.8155
test/c2st/auc            0.8992
test/c2st/gene_acc       0.7632
test/c2st/gene_auc       0.8380
test/c2st/nn             0.1210
test/c2st/nn_real_ref    0.1463
test/c2st/nn_std         0.1041
test/ct/acc              0.4219
test/ct/acc_gap          0.1974
test/ct/acc_gen          0.3926
test/ct/acc_real         0.5900
test/ct/f1               0.3958
test/ct/prop_jsd         0.0094
test/ct/prop_kl          0.1988
test/ct/prop_tv          0.0898
test/mmd2/pos            0.0843
test/mmd2/x              0.0288
test/moran/corr          -0.1796
test/moran/gen_mean      -0.0005
test/moran/mae           0.1892
test/moran/real_mean     0.1887
test/ot_w1/pos           0.4412
test/ot_w1/x             4.6008
test/ot_w2/pos           0.5210
test/ot_w2/x             4.8617
test/pos/mae             1.3198
test/pos/mse             2.5922
test/recon/mse_gap       0.2109
test/recon/mse_gen       0.6647
test/recon/mse_real      0.8756
test/x/mae               0.9918
test/x/mse               1.6855
notes: coords auto -> passthrough (generated per-axis std [1.2000000476837158, 1.2799999713897705] vs target raw std [0.49, 0.73]; standardised coords have std ~1); ct/acc_real from a fixed seeded sample of 2000 real target centroids (model-independent), not the generated-centroid pairing; recon/mse_real from a fixed seeded sample of 2000 real target centroids (model-independent), not the generated-centroid pairing

saved reports/wfm_expr_transformer_seed0/metrics_wfm_npc50.csv

### 4.8 WFM Transformer — expression + relative coordinates

In [29]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/wfm_joint_relxy_transformer_seed0/generated.npz \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/wfm_joint_relxy_transformer_seed0/metrics_wfm_npc50.csv

warning: `VIRTUAL_ENV=/work/magroup/shared/enfuzers/generative_modeling/.venv` does not match the project environment path `.venv` and will be ignored; use `--active` to target the active environment instead
<frozen runpy>:128: RuntimeWarning: 'paired_slides_eval.evaluate' found in sys.modules after import of package 'paired_slides_eval', but prior to execution of 'paired_slides_eval.evaluate'; this may result in unpredictable behaviour
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/.venv/lib/python3.12/site-packages/docrep/decorators.py:43: SyntaxWarning: 'n_jobs' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/.venv/lib/python3.12/site-packages/docrep/decorators.py:43: SyntaxWarning: 'show_progress_bar' is not a valid key!
  doc = func(self, args[0].__doc__, *args[1:], **kwargs)
/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/src/paired_slides_eval/metrics/morans.py:50: FutureWarning: Calling `spatial_neighbors` is deprecated and will be removed in squidpy v1.9.0. Use `spatial_neighbors_knn`, `spatial_neighbors_radius`, `spatial_neighbors_delaunay`, `spatial_neighbors_grid`, or `spatial_neighbors_from_builder` instead.
  sq.gr.spatial_neighbors(adata, coord_type="generic", n_neighs=n_neighs)

INFO     Creating graph using `None` transform and `1` libraries.

/work/magroup/shared/enfuzers/generative_modeling/eval_metrics/src/paired_slides_eval/metrics/morans.py:50: FutureWarning: Calling `spatial_neighbors` is deprecated and will be removed in squidpy v1.9.0. Use `spatial_neighbors_knn`, `spatial_neighbors_radius`, `spatial_neighbors_delaunay`, `spatial_neighbors_grid`, or `spatial_neighbors_from_builder` instead.
  sq.gr.spatial_neighbors(adata, coord_type="generic", n_neighs=n_neighs)

INFO     Creating graph using `None` transform and `1` libraries.
target: 9962 cells, 50 features
generated: 512 niches x 68 points
test/c2st/acc            0.7512
test/c2st/auc            0.8431
test/c2st/gene_acc       0.7392
test/c2st/gene_auc       0.8069
test/c2st/nn             0.1569
test/c2st/nn_real_ref    0.1815
test/c2st/nn_std         0.1063
test/ct/acc              0.3613
test/ct/acc_gap          0.2580
test/ct/acc_gen          0.3320
test/ct/acc_real         0.5900
test/ct/f1               0.3684
test/ct/prop_jsd         0.0117
test/ct/prop_kl          0.0508
test/ct/prop_tv          0.0918
test/mmd2/pos            0.0004
test/mmd2/x              0.0226
test/moran/corr          0.8882
test/moran/gen_mean      0.0228
test/moran/mae           0.1659
test/moran/real_mean     0.1887
test/ot_w1/pos           0.0961
test/ot_w1/x             4.6566
test/ot_w2/pos           0.1198
test/ot_w2/x             4.8710
test/pos/mae             0.1292
test/pos/mse             0.0272
test/recon/mse_gap       0.1590
test/recon/mse_gen       0.7166
test/recon/mse_real      0.8756
test/x/mae               1.0105
test/x/mse               1.7492
notes: coords auto -> passthrough (generated per-axis std [1.0299999713897705, 0.9800000190734863] vs target raw std [0.49, 0.73]; standardised coords have std ~1); ct/acc_real from a fixed seeded sample of 2000 real target centroids (model-independent), not the generated-centroid pairing; recon/mse_real from a fixed seeded sample of 2000 real target centroids (model-independent), not the generated-centroid pairing

saved reports/wfm_joint_relxy_transformer_seed0/metrics_wfm_npc50.csv

### 4.9 WFM faithful Transformer — expression only

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/wfm_expr_transformer_faithful_seed0/generated.npz \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/wfm_expr_transformer_faithful_seed0/metrics_wfm_npc50.csv

### 4.10 WFM faithful Transformer — expression + relative coordinates

In [ ]:
%%bash
set -euo pipefail
cd ..  # -> eval_metrics/
uv run python -m paired_slides_eval.evaluate \
  --target data/abca_pair.pkl \
  --generated artifacts/wfm_joint_relxy_transformer_faithful_seed0/generated.npz \
  --classifier ckpts/clf_gene.ckpt --ct_real_reference fixed \
  --regressor ckpts/recon_spatial.ckpt \
  --ct_key class --flat_pairing fixed_target_ot \
  --groups regression distribution c2st c2st_nn moran concordance ct_gap recon \
  --out reports/wfm_joint_relxy_transformer_faithful_seed0/metrics_wfm_npc50.csv

## 5. Compile metrics

Compile the six WFM metric CSVs into a new comparison table that preserves the existing four-architecture result file.

In [5]:
import os
from pathlib import Path

import pandas as pd

WFM_MODELS = [
    "wfm_expr_converged_seed0",
    "wfm_joint_relxy_converged_seed0",
    "wfm_expr_transformer_seed0",
    "wfm_joint_relxy_transformer_seed0",
    "wfm_expr_transformer_faithful_seed0",
    "wfm_joint_relxy_transformer_faithful_seed0",
]

cols = {}
missing = []
for name in WFM_MODELS:
    csv_path = Path("../reports") / name / "metrics_wfm_npc50.csv"
    if not csv_path.exists():
        missing.append(str(csv_path))
        continue
    cols[name] = pd.read_csv(csv_path, index_col="metric")["value"]

if missing:
    raise FileNotFoundError("Missing WFM metric CSV(s):\n" + "\n".join(missing))

wfm_table = pd.DataFrame(cols).sort_index()
out = Path("../reports/wfm_model_comparison_with_faithful_full_metrics.csv")
wfm_table.to_csv(out)
print(f"wrote {out}")
wfm_table

wrote ../reports/wfm_model_comparison_full_metrics.csv

,wfm_expr_converged_seed0,wfm_joint_relxy_converged_seed0,wfm_expr_transformer_seed0,wfm_joint_relxy_transformer_seed0
metric,,,,
test/c2st/acc,0.734500,0.685500,0.815500,0.751250
test/c2st/auc,0.804988,0.736827,0.899187,0.843131
test/c2st/gene_acc,0.620500,0.643250,0.763250,0.739250
test/c2st/gene_auc,0.660639,0.687048,0.838045,0.806940
test/c2st/nn,0.476650,0.448750,0.120950,0.156900
test/c2st/nn_real_ref,0.717600,0.726700,0.146300,0.181450
test/c2st/nn_std,0.151459,0.155269,0.104097,0.106266
test/ct/acc,0.433594,0.431641,0.421875,0.361328
test/ct/acc_gap,0.175937,0.185703,0.197422,0.257969
test/ct/acc_gen,0.414062,0.404297,0.392578,0.332031
test/ct/acc_real,0.590000,0.590000,0.590000,0.590000
test/ct/f1,0.414680,0.410557,0.395810,0.368422
test/ct/prop_jsd,0.010461,0.013890,0.009373,0.011730
test/ct/prop_kl,0.202687,0.218011,0.198788,0.050798
test/ct/prop_tv,0.097656,0.115234,0.089844,0.091797
test/mmd2/pos,0.084323,0.000373,0.084323,0.000381
test/mmd2/x,0.008360,0.008461,0.028769,0.022563
test/moran/corr,-0.316259,0.891870,-0.179600,0.888214
test/moran/gen_mean,-0.000113,0.013080,-0.000541,0.022824
test/moran/mae,0.188795,0.175601,0.189223,0.165857
test/moran/real_mean,0.188681,0.188681,0.188681,0.188681
test/ot_w1/pos,0.441183,0.097417,0.441183,0.096108
test/ot_w1/x,5.646253,5.674463,4.600839,4.656617
test/ot_w2/pos,0.521040,0.121437,0.521040,0.119814
test/ot_w2/x,5.750648,5.773073,4.861697,4.870975
test/pos/mae,1.319821,0.127739,1.319821,0.129193
test/pos/mse,2.592175,0.026127,2.592175,0.027231
test/recon/mse_gap,0.057117,0.062191,0.210874,0.159014
test/recon/mse_gen,0.818476,0.813402,0.664718,0.716579
test/recon/mse_real,0.875593,0.875593,0.875593,0.875593
test/x/mae,1.043054,1.040388,0.991763,1.010537
test/x/mse,1.833304,1.822824,1.685471,1.749169

In [7]:
import os
from pathlib import Path

import pandas as pd

MODELS = {
    "otcfm_shared50_1025",
    "otcfm_spatial_shared50_1025",
    "nicheflow_cfm_unaligned",
    "nicheflow_vfm_unaligned",
}

cols = {}
missing = []
for name in MODELS:
    csv_path = Path("../reports") / name / "metrics_npc50_full.csv"
    if not csv_path.exists():
        missing.append(str(csv_path))
        continue
    cols[name] = pd.read_csv(csv_path, index_col="metric")["value"]

if missing:
    raise FileNotFoundError("Missing WFM metric CSV(s):\n" + "\n".join(missing))

table = pd.DataFrame(cols).sort_index()
out = Path("../reports/model_comparison_50.csv")
table.to_csv(out)
print(f"wrote {out}")
table

wrote ../reports/model_comparison_50.csv

,nicheflow_vfm_unaligned,otcfm_spatial_shared50_1025,nicheflow_cfm_unaligned,otcfm_shared50_1025
metric,,,,
test/c2st/acc,0.558960,0.583005,0.829968,0.640041
test/c2st/auc,0.585323,0.621594,0.897919,0.706971
test/c2st/gene_acc,0.534984,0.541014,0.791001,0.595017
test/c2st/gene_auc,0.556017,0.589827,0.868916,0.613327
test/c2st/nn,0.301800,0.535800,0.050400,0.549800
test/c2st/nn_real_ref,0.357400,0.616000,0.975800,0.583600
test/c2st/nn_std,0.133629,0.165101,0.078612,0.156269
test/ct/acc,0.399610,0.434698,0.259259,0.331384
test/ct/acc_gap,0.328791,0.215731,0.359981,0.283957
test/ct/acc_gen,0.261209,0.374269,0.230019,0.306043
test/ct/acc_real,0.590000,0.590000,0.590000,0.590000
test/ct/f1,0.372114,0.410340,0.255479,0.264691
test/ct/prop_jsd,0.011330,0.021363,0.011820,0.067490
test/ct/prop_kl,0.047849,0.202540,0.160115,0.438594
test/ct/prop_tv,0.140351,0.165692,0.093567,0.298246
test/mmd2/pos,0.026263,0.008577,0.005469,0.045243
test/mmd2/x,0.006358,0.011044,0.036651,0.009858
test/moran/corr,0.967713,0.829468,0.688205,-0.142176
test/moran/gen_mean,0.189936,0.030282,0.081834,-0.001011
test/moran/mae,0.025144,0.158400,0.123791,0.189693
test/moran/real_mean,0.188681,0.188681,0.188681,0.188681
test/ot_w1/pos,0.315440,0.237052,0.326545,0.418850
test/ot_w1/x,6.059436,6.293791,7.638576,6.250489
test/ot_w2/pos,0.371333,0.288486,0.379374,0.487046
test/ot_w2/x,6.324937,6.449007,7.741431,6.392978
test/recon/mse_gap,0.039223,0.020463,0.005127,0.061441
test/recon/mse_gen,0.836370,0.896056,0.880720,0.937034
test/recon/mse_real,0.875593,0.875593,0.875593,0.875593

## 6. UMAP overlay — generated vs target

A qualitative companion to the distributional metrics. One UMAP is fit once on the target slide's shared whitened `X_pca(50)`, and each model's generated cells are projected through that frozen embedding so all panels share one coordinate frame.

In [ ]:
from paired_slides_eval.viz import umap_compare

MODELS = [
    ("otcfm",          "../artifacts/otcfm_shared50_1025/generated.h5ad"),
    ("otcfm_spatial",  "../artifacts/otcfm_spatial_shared50_1025/generated.h5ad"),
    ("nicheflow_cfm",  "../artifacts/nicheflow_cfm_unaligned/generated.h5ad"),
    ("nicheflow_vfm",  "../artifacts/nicheflow_vfm_unaligned/generated.h5ad"),
]

fig = umap_compare(
    "../data/abca_pair.pkl", MODELS,
    out_path="../reports/umap_compare.png",
    seed=0, point_size=3, alpha=0.5,   # lower point_size/alpha if the "all cells" plot is too dense
)
fig  # displays inline